artifact_uri: file:///c:/Users/Abdullah/Desktop/ecommerce-intelligence/notebooks/../mlflow/949158169714174170/6c506e0b740c4eaa8972bc3ea09983f3/artifacts
end_time: 1776795635320
entry_point_name: ''
experiment_id: '949158169714174170'
lifecycle_stage: active
run_id: 6c506e0b740c4eaa8972bc3ea09983f3
run_name: xgboost-v1
source_name: ''
source_type: 4
source_version: ''
start_time: 1776795624415
status: 3
tags: []
user_id: Abdullah
