FROM python:3.11-slim

WORKDIR /app

ENV PIP_DEFAULT_TIMEOUT=300
ENV PIP_RETRIES=5

COPY requirements_full.txt .

RUN pip install --no-cache-dir --timeout=300 -r requirements_full.txt

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", \
    "--no-browser", "--allow-root", "--NotebookApp.token=''"]