artifact_location: file:///c:/Users/Abdullah/Desktop/ecommerce-intelligence/notebooks/../mlflow/949158169714174170
creation_time: 1776795137620
experiment_id: '949158169714174170'
last_update_time: 1776795137620
lifecycle_stage: active
name: satisfaction-prediction
trace_location: null
workspace: default
