artifact_uri: file:///c:/Users/Abdullah/Desktop/ecommerce-intelligence/notebooks/../mlflow/949158169714174170/4ee7e1cd9196450b98b3191c3d5af580/artifacts
end_time: 1776871419120
entry_point_name: ''
experiment_id: '949158169714174170'
lifecycle_stage: active
run_id: 4ee7e1cd9196450b98b3191c3d5af580
run_name: xgboost-v1
source_name: ''
source_type: 4
source_version: ''
start_time: 1776871406442
status: 3
tags: []
user_id: Abdullah
